name: Minerador Industrial

on: [workflow_dispatch]

jobs:
  minerador:
    runs-on: ubuntu-latest
    timeout-minutes: 1440
    steps:
      - uses: actions/checkout@v4
      
      - name: Instalar dependências de sistema
        run: |
          sudo apt update
          sudo apt install -y libtorrent-rasterbar-dev python3-libtorrent
          
      - name: Instalar dependências Python
        run: |
          pip install psycopg[binary]
          
      - name: Executar Processamento
        env:
          DB_URL: ${{ secrets.DB_URL }}
        run: python minerador.py
